apiVersion: v1
kind: Secret
metadata:
  name: notice-board-secret
  namespace: digital-notice-board
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "replace_with_secure_production_db_password"
  JWT_SECRET: "replace_with_64_character_cryptographically_secure_jwt_secret_key"
